apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudsecops.fullname" . }}-secrets
  labels:
    {{- include "cloudsecops.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.backend.secrets.JWT_SECRET | b64enc | quote }}
  azure-subscription-id: {{ .Values.backend.secrets.AZURE_SUBSCRIPTION_ID | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudsecops.fullname" . }}-test-configs
  labels:
    {{- include "cloudsecops.labels" . | nindent 4 }}
data:
  terraform-example.tf: |
    # Terraform配置示例
    resource "aws_s3_bucket" "example" {
      bucket = "my-example-bucket"
    }
    
    resource "aws_s3_bucket_public_access_block" "example" {
      bucket = aws_s3_bucket.example.id
      
      block_public_acls       = false  # 安全风险：允许公共ACL
      block_public_policy     = false  # 安全风险：允许公共策略
      ignore_public_acls      = false
      restrict_public_buckets = false
    }
  
  cloudformation-example.yaml: |
    # CloudFormation配置示例
    AWSTemplateFormatVersion: '2010-09-09'
    Resources:
      MyS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: my-example-bucket
          PublicReadPolicy: Allow  # 安全风险：允许公共读取
  
  kubernetes-example.yaml: |
    # Kubernetes配置示例
    apiVersion: v1
    kind: Pod
    metadata:
      name: example-pod
    spec:
      containers:
      - name: app
        image: nginx:latest
        securityContext:
          runAsUser: 0  # 安全风险：以root用户运行
          privileged: true  # 安全风险：特权模式
        ports:
        - containerPort: 80
          hostPort: 80  # 安全风险：使用主机端口