{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudsecops.fullname" . }}-backend
  labels:
    {{- include "cloudsecops.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloudsecops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudsecops.fullname" . }}-frontend
  labels:
    {{- include "cloudsecops.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloudsecops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}