import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译数据类型定义
type TranslationKeys = {
  [key: string]: string;
};

type Translations = {
  zh: TranslationKeys;
  en: TranslationKeys;
};

// 翻译数据
const translations: Translations = {
  zh: {
    // 通用
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.view': '查看',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.export': '导出',
    'common.import': '导入',
    'common.refresh': '刷新',
    'common.loading': '加载中...',
    'common.noData': '暂无数据',
    'common.error': '错误',
    'common.success': '成功',
    'common.warning': '警告',
    'common.info': '信息',
    'common.close': '关闭',
    'common.all': '全部',
    'common.actions': '操作',
    'common.critical': '严重',
    'common.high': '高危',
    'common.medium': '中危',
    'common.low': '低危',
    
    // 导航栏
    'nav.dashboard': '仪表板',
    'nav.iacScanner': 'IaC安全扫描',
    'nav.monitor': '实时监控',
    'nav.attackChain': '攻击链分析',
    'nav.reports': '安全报告',
    'nav.remediation': '修复建议',
    'nav.cloudManagement': '云资源管理',
    'nav.profile': '个人资料',
    'nav.logout': '退出登录',
    'nav.darkMode': '深色模式',
    'nav.lightMode': '浅色模式',
    'nav.welcome': '欢迎',
    
    // 登录页面
    'login.title': '云安全运营平台',
    'login.subtitle': '企业级云安全管理解决方案',
    'login.username': '用户名',
    'login.password': '密码',
    'login.loginButton': '登录',
    'login.forgotPassword': '忘记密码？',
    'login.rememberMe': '记住我',
    'login.testAccount': '测试账号',
    'login.adminAccount': '管理员账号',
    'login.usernamePasswordRequired': '请输入用户名和密码',
    'login.invalidCredentials': '用户名或密码错误',
    
    // 仪表板
    'dashboard.title': '安全态势总览',
    'dashboard.lastUpdate': '最后更新',
    'dashboard.refreshData': '刷新数据',
    'dashboard.totalScans': '总扫描次数',
    'dashboard.criticalVulns': '严重漏洞',
    'dashboard.activeMonitors': '活跃监控',
    'dashboard.cloudResources': '云资源',
    'dashboard.vulnerabilityTrend': '漏洞趋势分析',
    'dashboard.severityDistribution': '漏洞严重程度分布',
    'dashboard.recentScans': '最近扫描结果',
    'dashboard.projectName': '项目名称',
    'dashboard.status': '状态',
    'dashboard.vulnerabilityCount': '漏洞数量',
    'dashboard.severity': '严重程度',
    'dashboard.scanTime': '扫描时间',
    'dashboard.completed': '已完成',
    'dashboard.running': '运行中',
    'dashboard.failed': '失败',
    'dashboard.critical': '严重',
    'dashboard.high': '高危',
    'dashboard.medium': '中危',
    'dashboard.low': '低危',
    'dashboard.minutesAgo': '分钟前',
    'dashboard.unknown': '未知',
    'dashboard.monday': '周一',
    'dashboard.tuesday': '周二',
    'dashboard.wednesday': '周三',
    'dashboard.thursday': '周四',
    'dashboard.friday': '周五',
    'dashboard.saturday': '周六',
    'dashboard.sunday': '周日',
    
    // IaC扫描
    'iac.title': 'IaC 安全扫描',
    'iac.uploadFiles': '上传配置文件',
    'iac.dragDropFiles': '拖放文件或点击选择',
    'iac.supportedFiles': '支持 .tf, .yaml, .yml, .json 文件',
    'iac.selectedFiles': '已选择文件:',
    'iac.startScan': '开始扫描',
    'iac.scanning': '扫描中...',
    'iac.scanStats': '扫描统计',
    'iac.totalScans': '总扫描数',
    'iac.highVulns': '高危漏洞',
    'iac.scanInProgress': '扫描进行中...',
    'iac.scanResults': '扫描结果',
    'iac.noResults': '暂无扫描结果，请上传文件并开始扫描。',
    'iac.fileName': '文件名',
    'iac.type': '类型',
    'iac.status': '状态',
    'iac.critical': '严重',
    'iac.high': '高危',
    'iac.medium': '中危',
    'iac.low': '低危',
    'iac.info': '信息',
    'iac.s3PublicAccess': 'S3存储桶允许公共访问',
    'iac.s3PublicAccessDesc': '检测到S3存储桶配置允许公共读取访问，可能导致数据泄露。',
    'iac.s3PublicAccessRemediation': '设置适当的存储桶策略，限制公共访问权限。',
    'iac.containerPrivileged': '容器以特权模式运行',
    'iac.containerPrivilegedDesc': '容器配置为特权模式运行，可能导致容器逃逸。',
    'iac.containerPrivilegedRemediation': '移除privileged: true配置，使用最小权限原则。',
     'iac.scanTime': '扫描时间',
    'iac.actions': '操作',
    'iac.completed': '已完成',
    'iac.failed': '失败',
    'iac.waiting': '等待中',
    'iac.viewDetails': '查看详情',
    'iac.scanDetails': '扫描详情',
    'iac.rule': '规则',
    'iac.location': '位置',
    'iac.description': '描述',
    'iac.remediation': '修复建议',
    'iac.close': '关闭',
    
    // 攻击链分析
    'attackChain.title': '攻击链分析',
    'attackChain.analysisType': '分析类型',
    'attackChain.fullAnalysis': '完整分析',
    'attackChain.quickAnalysis': '快速分析',
    'attackChain.targetedAnalysis': '定向分析',
    'attackChain.startAnalysis': '开始分析',
    'attackChain.analyzing': '分析中...',
    'attackChain.analyzingPath': '正在分析攻击路径，请稍候...',
    'attackChain.analysisTitle': '攻击链分析',
    'attackChain.hours': '小时',
    'attackChain.totalChains': '攻击链总数',
    'attackChain.highRiskChains': '高风险链',
    'attackChain.avgRiskScore': '平均风险分',
    'attackChain.analysisStatus': '分析状态',
    'attackChain.ready': '就绪',
    'attackChain.chainList': '攻击链列表',
    'attackChain.noChains': '暂无攻击链分析结果，点击"开始分析"按钮生成攻击链。',
    'attackChain.name': '名称',
    'attackChain.riskScore': '风险评分',
    'attackChain.attackSteps': '攻击步骤',
    'attackChain.criticalVulns': '关键漏洞',
    'attackChain.successRate': '成功概率',
    'attackChain.status': '状态',
    'attackChain.createdAt': '创建时间',
    'attackChain.actions': '操作',
    'attackChain.completed': '已完成',
    'attackChain.failed': '失败',
    'attackChain.viewChain': '查看攻击链',
    'attackChain.chainDetails': '攻击链详情',
    'attackChain.attackPath': '攻击路径图',
    'attackChain.stepDetails': '攻击步骤详情',
    'attackChain.severity': '严重程度',
    'attackChain.description': '描述',
    'attackChain.remediation': '修复建议',
    'attackChain.close': '关闭',
    'attackChain.veryHigh': '极高',
    'attackChain.high': '高',
    'attackChain.medium': '中',
    'attackChain.low': '低',
    'attackChain.initialAccess': '初始访问',
    'attackChain.privilegeDiscovery': '权限发现',
    'attackChain.privilegeEscalation': '权限提升',
    'attackChain.lateralMovement': '横向移动',
    'attackChain.persistence': '持久化',
    'attackChain.dataExfiltration': '数据窃取',
    'attackChain.sqlInjectionDesc': '通过SQL注入漏洞获得初始访问权限',
    'attackChain.sqlInjectionRemediation': '修复SQL注入漏洞，使用参数化查询',
    'attackChain.userEnumerationDesc': '枚举系统用户和权限信息',
    'attackChain.userEnumerationRemediation': '限制用户枚举，加强访问控制',
    'attackChain.dbPrivilegeEscDesc': '利用数据库权限提升漏洞获得更高权限',
    'attackChain.dbPrivilegeEscRemediation': '修复权限提升漏洞，实施最小权限原则',
    'attackChain.networkScanDesc': '扫描内网寻找其他可攻击目标',
    'attackChain.networkScanRemediation': '网络分段，限制横向移动',
    'attackChain.backdoorDesc': '植入后门程序维持持久化访问',
    'attackChain.backdoorRemediation': '定期检查系统完整性，监控异常进程',
    'attackChain.dataTheftDesc': '窃取敏感数据并外传',
    'attackChain.dataTheftRemediation': '数据加密，监控数据外传行为',
    

    
    // 修复建议
    'remediation.title': '智能修复建议',
    'remediation.refresh': '刷新',
    'remediation.totalSuggestions': '总建议数',
    'remediation.pending': '待处理',
    'remediation.applied': '已应用',
    'remediation.failed': '应用失败',
    'remediation.suggestionList': '修复建议列表',
    'remediation.noSuggestions': '暂无修复建议',
    'remediation.title2': '标题',
    'remediation.filePath': '文件路径',
    'remediation.severity': '严重程度',
    'remediation.status': '状态',
    'remediation.createTime': '创建时间',
    'remediation.actions': '操作',
    'remediation.viewDetails': '查看详情',
    'remediation.applyFix': '应用修复',
    'remediation.suggestionDetails': '修复建议详情',
    'remediation.problemDesc': '问题描述',
    'remediation.fixSuggestion': '修复建议',
    'remediation.fixCode': '修复代码',
    'remediation.errorInfo': '错误信息',
    'remediation.applyFixBtn': '应用修复',
    'remediation.close': '关闭',
    'remediation.loadedSampleData': '已加载示例修复建议数据',
    'remediation.loadDetailsFailed': '加载修复建议详情失败',
    'remediation.applySuccess': '修复建议应用成功',
    'remediation.applyFailed': '应用修复建议失败',
    
    // 报告
    'reports.title': '安全报告',
    'reports.reportType': '报告类型',
    'reports.securityAssessment': '安全评估',
    'reports.vulnerabilityScan': '漏洞扫描',
    'reports.attackChainAnalysis': '攻击链分析',
    'reports.complianceCheck': '合规检查',
    'reports.monitoringReport': '监控报告',
    'reports.timeRange': '时间范围',
    'reports.oneDay': '1天',
    'reports.sevenDays': '7天',
    'reports.thirtyDays': '30天',
    'reports.ninetyDays': '90天',
    'reports.generateReport': '生成报告',
    'reports.generating': '生成中...',
      // Cloud Management
      'cloud.title': '云资源管理',
      'cloud.syncSuccess': '资源同步成功',
      'cloud.syncFailed': '资源同步失败',
      'cloud.exportSuccess': '导出成功',
      'cloud.exportFailed': '导出失败',
      'cloud.loadDetailsFailed': '加载详情失败',
      'cloud.mockDataLoaded': '已加载示例数据',
      'cloud.syncing': '同步中...',
      'cloud.syncResources': '同步资源',
      'cloud.exportResources': '导出资源',
      'cloud.syncingProgress': '正在同步资源...',
      'cloud.awsResources': 'AWS 资源',
      'cloud.azureResources': 'Azure 资源',
      'cloud.securityScore': '安全评分',
      'cloud.complianceRate': '合规率',
      'cloud.resourceDistribution': '资源分布',
      'cloud.securityIssuesDistribution': '安全问题分布',
      'cloud.critical': '严重',
      'cloud.high': '高危',
      'cloud.medium': '中危',
      'cloud.low': '低危',
      'cloud.resourceManagement': '资源管理',
      'cloud.resourceType': '资源类型',
      'cloud.virtualMachine': '虚拟机',
      'cloud.storage': '存储',
      'cloud.resourceName': '资源名称',
      'cloud.type': '类型',
      'cloud.region': '区域',
      'cloud.status': '状态',
      'cloud.createdAt': '创建时间',
      'cloud.actions': '操作',
      'cloud.viewDetails': '查看详情',
      'cloud.securityRecommendations': '安全建议',
      'cloud.resourceDetails': '资源详情',
      'cloud.resourceId': '资源ID',
      'cloud.lastModified': '最后修改',
      'cloud.tags': '标签',
      'cloud.enableMFA': '启用多因素认证',
      'cloud.updateSSLCert': '更新SSL证书',
    
    // 监控
    'monitor.title': '运行时监控',
    'monitor.autoRefresh': '自动刷新',
    'monitor.startMonitoring': '开始监控',
    'monitor.stopMonitoring': '停止监控',
    'monitor.startMonitoringTip': '点击"开始监控"按钮启动eBPF运行时监控。',
    'monitor.totalEvents': '总事件数',
    'monitor.criticalEvents': '高危事件',
    'monitor.activeContainers': '活跃容器',
    'monitor.monitoringStatus': '监控状态',
    'monitor.running': '运行中',
    'monitor.stopped': '已停止',
    'monitor.realTimeEventTrend': '实时事件趋势',
    'monitor.systemResources': '系统资源',
    'monitor.cpuUsage': 'CPU使用率',
    'monitor.memoryUsage': '内存使用率',
    'monitor.monitoringEvents': '监控事件',
    'monitor.critical': '严重',
    'monitor.high': '高危',
    'monitor.noEvents': '暂无监控事件',
    'monitor.pleaseStartMonitoring': '请先启动监控',
    'monitor.time': '时间',
    'monitor.container': '容器',
    'monitor.eventType': '事件类型',
    'monitor.severity': '严重程度',
    'monitor.message': '消息',
    'monitor.actions': '操作',
    'monitor.viewDetails': '查看详情',
    'monitor.eventDetails': '事件详情',
    'monitor.eventId': '事件ID',
    'monitor.details': '详细信息',
    'monitor.fileAccessAction': '访问敏感文件 /etc/passwd',
    'monitor.networkAction': '建立可疑网络连接',
    'monitor.processAction': '启动特权进程',
    'monitor.syscallAction': '执行危险系统调用',
    
    // 个人资料
    'profile.title': '个人资料',
    'profile.editProfile': '编辑资料',
    'profile.saveChanges': '保存更改',
    'profile.cancel': '取消',
    'profile.changePassword': '修改密码',
    'profile.basicInfo': '基本信息',
    'profile.username': '用户名',
    'profile.email': '邮箱',
    'profile.fullName': '姓名',
    'profile.phone': '电话',
    'profile.department': '部门',
    'profile.position': '职位',
    'profile.location': '地址',
    'profile.joinDate': '入职日期',
    'profile.lastLogin': '最后登录',
    'profile.role': '角色',
    'profile.permissions': '权限',
    'profile.preferences': '偏好设置',
    'profile.emailNotifications': '邮件通知',
    'profile.smsNotifications': '短信通知',
    'profile.securityAlerts': '安全警报',
    'profile.reportNotifications': '报告通知',
    'profile.currentPassword': '当前密码',
    'profile.newPassword': '新密码',
    'profile.confirmPassword': '确认密码',
    'profile.saveFailed': '保存失败，请重试',
    'profile.passwordMismatch': '新密码与确认密码不匹配',
    'profile.passwordChangeFailed': '密码修改失败，请重试',
    'profile.systemAdmin': '系统管理员',
    'profile.securityDept': '安全部门',
    'profile.seniorSecurityEngineer': '高级安全工程师',
    'profile.beijing': '北京朝阳区',
    'profile.admin': '管理员',
    'profile.systemManagement': '系统管理',
    'profile.userManagement': '用户管理',
    'profile.securityScanning': '安全扫描',
    'profile.reportGeneration': '报告生成',
    'profile.monitoringManagement': '监控管理',
    'profile.seniorUser': '高级用户',
    'profile.regularUser': '普通用户',
    'profile.save': '保存',
    'profile.saveSuccess': '信息保存成功！',
    'profile.address': '地址',
    'profile.securitySettings': '安全设置',
    'profile.joinTime': '加入时间',
    'profile.permissionManagement': '权限管理',
    'profile.notificationSettings': '通知设置',
    'profile.emailNotification': '邮件通知',
    'profile.smsNotification': '短信通知',
    'profile.securityAlert': '安全警报',
    'profile.reportNotification': '报告通知',
    'profile.changePasswordTitle': '修改密码',
    'profile.confirmChange': '确认修改',
  },
  en: {
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.loading': 'Loading...',
    'common.noData': 'No Data',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.close': 'Close',
    'common.all': 'All',
    'common.actions': 'Actions',
    'common.critical': 'Critical',
    'common.high': 'High',
    'common.medium': 'Medium',
    'common.low': 'Low',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.iacScanner': 'IaC Security Scan',
    'nav.monitor': 'Real-time Monitor',
    'nav.attackChain': 'Attack Chain Analysis',
    'nav.reports': 'Security Reports',
    'nav.remediation': 'Remediation',
    'nav.cloudManagement': 'Cloud Management',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.darkMode': 'Dark Mode',
    'nav.lightMode': 'Light Mode',
    'nav.welcome': 'Welcome',
    
    // Login Page
    'login.title': 'Cloud Security Operations Platform',
    'login.subtitle': 'Enterprise Cloud Security Management Solution',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.loginButton': 'Login',
    'login.forgotPassword': 'Forgot Password?',
    'login.rememberMe': 'Remember Me',
    'login.testAccount': 'Test Account',
    'login.adminAccount': 'Admin Account',
    'login.usernamePasswordRequired': 'Please enter username and password',
    'login.invalidCredentials': 'Invalid username or password',
    
    // Dashboard
    'dashboard.title': 'Security Overview',
    'dashboard.lastUpdate': 'Last Update',
    'dashboard.refreshData': 'Refresh Data',
    'dashboard.totalScans': 'Total Scans',
    'dashboard.criticalVulns': 'Critical Vulnerabilities',
    'dashboard.activeMonitors': 'Active Monitors',
    'dashboard.cloudResources': 'Cloud Resources',
    'dashboard.vulnerabilityTrend': 'Vulnerability Trend Analysis',
    'dashboard.severityDistribution': 'Vulnerability Severity Distribution',
    'dashboard.recentScans': 'Recent Scan Results',
    'dashboard.projectName': 'Project Name',
    'dashboard.status': 'Status',
    'dashboard.vulnerabilityCount': 'Vulnerability Count',
    'dashboard.severity': 'Severity',
    'dashboard.scanTime': 'Scan Time',
    'dashboard.completed': 'Completed',
    'dashboard.running': 'Running',
    'dashboard.failed': 'Failed',
    'dashboard.critical': 'Critical',
    'dashboard.high': 'High',
    'dashboard.medium': 'Medium',
    'dashboard.low': 'Low',
    'dashboard.minutesAgo': 'minutes ago',
    'dashboard.unknown': 'Unknown',
    'dashboard.monday': 'Mon',
    'dashboard.tuesday': 'Tue',
    'dashboard.wednesday': 'Wed',
    'dashboard.thursday': 'Thu',
    'dashboard.friday': 'Fri',
    'dashboard.saturday': 'Sat',
    'dashboard.sunday': 'Sun',
    
    // IaC Scanner
    'iac.title': 'IaC Security Scanner',
    'iac.uploadFiles': 'Upload Configuration Files',
    'iac.dragDropFiles': 'Drag and drop files or click to select',
    'iac.supportedFiles': 'Supports .tf, .yaml, .yml, .json files',
    'iac.selectedFiles': 'Selected files:',
    'iac.startScan': 'Start Scan',
    'iac.scanning': 'Scanning...',
    'iac.scanStats': 'Scan Statistics',
    'iac.totalScans': 'Total Scans',
    'iac.highVulns': 'High Vulnerabilities',
    'iac.scanInProgress': 'Scan in progress...',
    'iac.scanResults': 'Scan Results',
    'iac.noResults': 'No scan results available. Please upload files and start scanning.',
    'iac.fileName': 'File Name',
    'iac.type': 'Type',
    'iac.status': 'Status',
    'iac.critical': 'Critical',
    'iac.high': 'High',
    'iac.medium': 'Medium',
    'iac.low': 'Low',
    'iac.info': 'Info',
    'iac.s3PublicAccess': 'S3 bucket allows public access',
    'iac.s3PublicAccessDesc': 'Detected S3 bucket configuration that allows public read access, which may lead to data leakage.',
    'iac.s3PublicAccessRemediation': 'Set appropriate bucket policies to restrict public access permissions.',
    'iac.containerPrivileged': 'Container running in privileged mode',
    'iac.containerPrivilegedDesc': 'Container is configured to run in privileged mode, which may lead to container escape.',
    'iac.containerPrivilegedRemediation': 'Remove privileged: true configuration and use the principle of least privilege.',
     'iac.scanTime': 'Scan Time',
    'iac.actions': 'Actions',
    'iac.completed': 'Completed',
    'iac.failed': 'Failed',
    'iac.waiting': 'Waiting',
    'iac.viewDetails': 'View Details',
    'iac.scanDetails': 'Scan Details',
    'iac.rule': 'Rule',
    'iac.location': 'Location',
    'iac.description': 'Description',
    'iac.remediation': 'Remediation',
    'iac.close': 'Close',
    
    // Attack Chain
    'attackChain.title': 'Attack Chain Analysis',
    'attackChain.analysisType': 'Analysis Type',
    'attackChain.fullAnalysis': 'Full Analysis',
    'attackChain.quickAnalysis': 'Quick Analysis',
    'attackChain.targetedAnalysis': 'Targeted Analysis',
    'attackChain.startAnalysis': 'Start Analysis',
    'attackChain.analyzing': 'Analyzing...',
    'attackChain.analysisProgress': 'Analyzing attack paths, please wait...',
    'attackChain.totalChains': 'Total Chains',
    'attackChain.highRiskChains': 'High Risk Chains',
    'attackChain.avgRiskScore': 'Average Risk Score',
    'attackChain.analysisStatus': 'Analysis Status',
    'attackChain.ready': 'Ready',
    'attackChain.chainList': 'Attack Chain List',
    'attackChain.noChains': 'No attack chain analysis results. Click "Start Analysis" to generate attack chains.',
    'attackChain.name': 'Name',
    'attackChain.riskScore': 'Risk Score',
    'attackChain.attackSteps': 'Attack Steps',
    'attackChain.criticalVulns': 'Key Vulnerabilities',
    'attackChain.successRate': 'Success Rate',
    'attackChain.status': 'Status',
    'attackChain.createdAt': 'Create Time',
    'attackChain.actions': 'Actions',
    'attackChain.completed': 'Completed',
    'attackChain.failed': 'Failed',
    'attackChain.viewChain': 'View Chain',
    'attackChain.chainDetails': 'Chain Details',
    'attackChain.attackPath': 'Attack Path Diagram',
    'attackChain.stepDetails': 'Step Details',
    'attackChain.severity': 'Severity',
    'attackChain.description': 'Description',
    'attackChain.remediation': 'Remediation',
    'attackChain.close': 'Close',
    'attackChain.veryHigh': 'Very High',
    'attackChain.high': 'High',
    'attackChain.medium': 'Medium',
    'attackChain.low': 'Low',
    'attackChain.initialAccess': 'Initial Access',
    'attackChain.privilegeDiscovery': 'Privilege Discovery',
    'attackChain.privilegeEscalation': 'Privilege Escalation',
    'attackChain.lateralMovement': 'Lateral Movement',
    'attackChain.persistence': 'Persistence',
    'attackChain.dataExfiltration': 'Data Exfiltration',
    'attackChain.sqlInjectionDesc': 'Gain initial access through SQL injection vulnerability',
    'attackChain.sqlInjectionRemediation': 'Fix SQL injection vulnerabilities, use parameterized queries',
    'attackChain.userEnumerationDesc': 'Enumerate system users and permission information',
    'attackChain.userEnumerationRemediation': 'Restrict user enumeration, strengthen access control',
    'attackChain.dbPrivilegeEscDesc': 'Exploit database privilege escalation vulnerability to gain higher privileges',
    'attackChain.dbPrivilegeEscRemediation': 'Fix privilege escalation vulnerabilities, implement principle of least privilege',
    'attackChain.networkScanDesc': 'Scan internal network for other attackable targets',
    'attackChain.networkScanRemediation': 'Network segmentation, restrict lateral movement',
    'attackChain.backdoorDesc': 'Plant backdoor programs to maintain persistent access',
    'attackChain.backdoorRemediation': 'Regularly check system integrity, monitor abnormal processes',
    'attackChain.dataTheftDesc': 'Steal sensitive data and exfiltrate',
    'attackChain.dataTheftRemediation': 'Data encryption, monitor data exfiltration behavior',
    
    // Monitor
      'monitor.title': 'Runtime Monitoring',
      'monitor.autoRefresh': 'Auto Refresh',
      'monitor.startMonitoring': 'Start Monitoring',
      'monitor.stopMonitoring': 'Stop Monitoring',
      'monitor.startMonitoringTip': 'Click "Start Monitoring" to enable eBPF runtime monitoring.',
      'monitor.totalEvents': 'Total Events',
      'monitor.criticalEvents': 'Critical Events',
      'monitor.activeContainers': 'Active Containers',
      'monitor.monitoringStatus': 'Monitoring Status',
      'monitor.running': 'Running',
      'monitor.stopped': 'Stopped',
      'monitor.realTimeEventTrend': 'Real-time Event Trend',
      'monitor.systemResources': 'System Resources',
      'monitor.cpuUsage': 'CPU Usage',
      'monitor.memoryUsage': 'Memory Usage',
      'monitor.monitoringEvents': 'Monitoring Events',
      'monitor.critical': 'Critical',
      'monitor.high': 'High',
      'monitor.noEvents': 'No monitoring events',
      'monitor.pleaseStartMonitoring': 'Please start monitoring first',
      'monitor.time': 'Time',
      'monitor.container': 'Container',
      'monitor.eventType': 'Event Type',
      'monitor.severity': 'Severity',
      'monitor.message': 'Message',
      'monitor.actions': 'Actions',
      'monitor.viewDetails': 'View Details',
      'monitor.eventDetails': 'Event Details',
      'monitor.eventId': 'Event ID',
      'monitor.details': 'Detailed Information',
      'monitor.fileAccessAction': 'Access sensitive file /etc/passwd',
      'monitor.networkAction': 'Establish suspicious network connection',
      'monitor.processAction': 'Start privileged process',
      'monitor.syscallAction': 'Execute dangerous system call',
    
    // Remediation
    'remediation.title': 'Smart Remediation Suggestions',
    'remediation.refresh': 'Refresh',
    'remediation.totalSuggestions': 'Total Suggestions',
    'remediation.pending': 'Pending',
    'remediation.applied': 'Applied',
    'remediation.failed': 'Failed',
    'remediation.suggestionList': 'Suggestion List',
    'remediation.noSuggestions': 'No remediation suggestions',
    'remediation.title2': 'Title',
    'remediation.filePath': 'File Path',
    'remediation.severity': 'Severity',
    'remediation.status': 'Status',
    'remediation.createTime': 'Create Time',
    'remediation.actions': 'Actions',
    'remediation.viewDetails': 'View Details',
    'remediation.applyFix': 'Apply Fix',
    'remediation.suggestionDetails': 'Suggestion Details',
    'remediation.problemDesc': 'Problem Description',
    'remediation.fixSuggestion': 'Fix Suggestion',
    'remediation.fixCode': 'Fix Code',
    'remediation.errorInfo': 'Error Information',
    'remediation.applyFixBtn': 'Apply Fix',
    'remediation.close': 'Close',
    'remediation.loadedSampleData': 'Sample remediation data loaded',
    'remediation.loadDetailsFailed': 'Failed to load suggestion details',
    'remediation.applySuccess': 'Remediation suggestion applied successfully',
    'remediation.applyFailed': 'Failed to apply remediation suggestion',
    
    // Reports
    'reports.title': 'Security Reports',
    'reports.reportType': 'Report Type',
    'reports.securityAssessment': 'Security Assessment',
    'reports.vulnerabilityScan': 'Vulnerability Scan',
    'reports.attackChainAnalysis': 'Attack Chain Analysis',
    'reports.complianceCheck': 'Compliance Check',
    'reports.monitoringReport': 'Monitoring Report',
    'reports.timeRange': 'Time Range',
    'reports.oneDay': '1 Day',
    'reports.sevenDays': '7 Days',
    'reports.thirtyDays': '30 Days',
    'reports.ninetyDays': '90 Days',
    'reports.generateReport': 'Generate Report',
    'reports.generating': 'Generating...',
    'reports.totalReports': 'Total Reports',
    'reports.completed': 'Completed',
    'reports.inProgress': 'In Progress',
    'reports.totalIssues': 'Total Issues',
    'reports.securityTrend': 'Security Trend Analysis',
    'reports.vulnerabilities': 'Vulnerabilities',
    'reports.resolved': 'Resolved',
    'reports.newIssues': 'New Issues',
    'reports.severityDistribution': 'Issue Severity Distribution',
    'reports.reportList': 'Report List',
    'reports.noReports': 'No reports available. Click "Generate Report" to create a new report.',
    'reports.reportName': 'Report Name',
    'reports.type': 'Type',
    'reports.status': 'Status',
    'reports.issueStats': 'Issue Statistics',
    'reports.fileSize': 'File Size',
    'reports.generatedBy': 'Generated By',
    'reports.createdAt': 'Created At',
    'reports.viewDetails': 'View Details',
    'reports.downloadPdf': 'Download PDF',
    'reports.downloadExcel': 'Download Excel',
    'reports.downloadJson': 'Download JSON',
    'reports.reportDetails': 'Report Details',
    'reports.issueDistribution': 'Issue Distribution Chart',
    'reports.securityReports': 'Security Reports',
    'reports.securityReport': 'Security Assessment Report',
    'reports.complianceReport': 'Compliance Check Report',
    'reports.vulnerabilityReport': 'Vulnerability Scan Report',
    'reports.attackChainReport': 'Attack Chain Analysis Report',
    'reports.monitorReport': 'Monitoring Report',
    'reports.unknownReport': 'Unknown Report',
    'reports.webApplication': 'Web Application',
    
    // Cloud Management
    'cloud.title': 'Multi-Cloud Management',
    'cloud.syncResources': 'Sync Resources',
    'cloud.syncing': 'Syncing...',
    'cloud.exportResources': 'Export Resources',
    'cloud.refresh': 'Refresh',
    'cloud.syncingProgress': 'Syncing cloud resources...',
    'cloud.awsResources': 'AWS Resources',
    'cloud.azureResources': 'Azure Resources',
    'cloud.securityScore': 'Security Score',
    'cloud.complianceRate': 'Compliance Rate',
    'cloud.resourceDistribution': 'Resource Distribution',
    'cloud.securityIssuesDistribution': 'Security Issues Distribution',
    'cloud.resourceManagement': 'Cloud Resource Management',
    'cloud.resourceType': 'Resource Type',
    'cloud.virtualMachine': 'Virtual Machine',
    'cloud.storage': 'Storage',
    'cloud.resourceName': 'Resource Name',
    'cloud.type': 'Type',
    'cloud.region': 'Region',
    'cloud.status': 'Status',
    'cloud.createdAt': 'Created At',
    'cloud.actions': 'Actions',
    'cloud.viewDetails': 'View Details',
    'cloud.securityRecommendations': 'Security Recommendations',
    'cloud.resourceDetails': 'Resource Details',
    'cloud.resourceId': 'Resource ID',
    'cloud.lastModified': 'Last Modified',
    'cloud.tags': 'Tags',
    'cloud.enableMFA': 'Enable Multi-Factor Authentication',
    'cloud.updateSSLCert': 'Update Expired SSL Certificate',
    'cloud.configureSecurityGroups': 'Configure Network Security Group Rules',
    'cloud.mockDataLoaded': 'Sample cloud resource data loaded',
    'cloud.exportSuccess': 'Resource export successful',
    'cloud.exportFailed': 'Resource export failed',
    'cloud.loadDetailsFailed': 'Failed to load resource details',
    
    // Profile
    'profile.title': 'Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.saveChanges': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.changePassword': 'Change Password',
    'profile.basicInfo': 'Basic Information',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.fullName': 'Full Name',
    'profile.phone': 'Phone',
    'profile.department': 'Department',
    'profile.position': 'Position',
    'profile.location': 'Location',
    'profile.joinDate': 'Join Date',
    'profile.lastLogin': 'Last Login',
    'profile.role': 'Role',
    'profile.permissions': 'Permissions',
    'profile.preferences': 'Preferences',
    'profile.emailNotifications': 'Email Notifications',
    'profile.smsNotifications': 'SMS Notifications',
    'profile.securityAlerts': 'Security Alerts',
    'profile.reportNotifications': 'Report Notifications',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm Password',
    'profile.saveSuccess': 'Saved successfully',
     'profile.saveFailed': 'Save failed, please try again',
     'profile.passwordMismatch': 'New password and confirm password do not match',
     'profile.passwordChangeFailed': 'Password change failed, please try again',
     'profile.systemAdmin': 'System Administrator',
     'profile.securityDept': 'Security Department',
     'profile.seniorSecurityEngineer': 'Senior Security Engineer',
     'profile.beijing': 'Beijing Chaoyang District',
     'profile.admin': 'Administrator',
     'profile.systemManagement': 'System Management',
     'profile.userManagement': 'User Management',
     'profile.securityScanning': 'Security Scanning',
     'profile.reportGeneration': 'Report Generation',
     'profile.monitoringManagement': 'Monitoring Management',
     'profile.seniorUser': 'Senior User',
     'profile.regularUser': 'Regular User',
     'profile.save': 'Save',
    'profile.address': 'Address',
    'profile.securitySettings': 'Security Settings',
    'profile.joinTime': 'Join Time',
    'profile.permissionManagement': 'Permission Management',
    'profile.notificationSettings': 'Notification Settings',
    'profile.emailNotification': 'Email Notification',
    'profile.smsNotification': 'SMS Notification',
    'profile.securityAlert': 'Security Alert',
    'profile.reportNotification': 'Report Notification',
    'profile.changePasswordTitle': 'Change Password',
    'profile.confirmChange': 'Confirm Change',
    'profile.normalUser': 'Normal User',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // 从localStorage获取保存的语言设置，默认为中文
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'zh';
  });

  // 当语言改变时保存到localStorage
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // 翻译函数
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook for using language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};